CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    description VARCHAR(255),
    img_url VARCHAR(255),
    is_deleted BOOLEAN,
    is_sycronized BOOLEAN,
    price NUMERIC(38,2),
    title VARCHAR(255),
    updated_at TIMESTAMP(6),
    user_id BIGINT,
    PRIMARY KEY (id)
);
