CREATE TABLE IF NOT EXISTS users (
   id bigint generated by default as identity,
    created_at timestamp(6),
    deleted_at timestamp(6),
    email varchar(255),
    is_deleted boolean,
    is_syncronized boolean,
    name varchar(255),
    password varchar(255),
    role varchar(255),
    updated_at timestamp(6),
    primary key (id)
);

